name: Run tests
on: [push]
jobs:
  build-and-test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Prepare go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Run tests
        run: go test ./...
